#!/usr/bin/env python3
"""
ligo_spectre_search.py -- a concrete, falsifiable search for an einstein-tile signature in strain data.

What "signature" means here
---------------------------
The spectre tiling is generated by a substitution with a fixed linear
inflation factor lambda (measured empirically below from the supertile quad
across iterations).  Any physical process organised by that hierarchy would
imprint a LOG-PERIODIC comb on a spectrum: lines at f_n = f0 * lambda^n.
Equal spacing in log-frequency is the fingerprint; the spacing is ln(lambda).

Pipeline
--------
1. Build spectre tilings at several iteration depths; measure lambda.
2. Compute the 1D structure factor S(k) of the tile centroids and verify the
   self-similar peak hierarchy with ratio lambda (the template's origin).
3. For a strain PSD: resample onto a uniform log-f grid, whiten by a running
   median, autocorrelate in log-f.  A comb with ratio lambda produces an
   autocorrelation peak at lag ln(lambda) (and multiples).
4. Score against phase-randomised surrogates -> z-score at lag ln(lambda).
5. Validate the whole pipeline by injecting a synthetic spectre comb.

Data sources, in order of preference:
  a) HDF5 files in ./ligo_cache
  b) live fetch via gwpy.TimeSeries.fetch_open_data (needs gwosc.org access)
  c) synthetic aLIGO-like coloured noise (so the pipeline always runs)

Honest framing: there is no established physics predicting this comb; this is
an exploratory search, and the null result is the expected outcome.  The
value of the script is that the statistic is well-defined and the injection
test proves we would see the signature if it were there.
"""
import os, glob
import numpy as np
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
from scipy.signal import welch, find_peaks

import tile_family as TF

OUT = os.environ.get('EINSTEIN3D_OUT', '/tmp')
RNG = np.random.default_rng(11)
CACHE = os.path.join(os.path.dirname(os.path.abspath(__file__)), 'ligo_cache')


# ===========================================================================
# 1) the inflation factor lambda of the spectre substitution
# ===========================================================================
def measure_inflation(max_iter=4):
    import spectre as S
    sizes = []
    for n in range(1, max_iter + 1):
        tiles = S.buildSpectreTiles(n, 1.0, 1.0)
        quad = tiles['Delta'].quad
        diag = np.linalg.norm(quad[2] - quad[0])
        sizes.append(diag)
    ratios = [sizes[i + 1] / sizes[i] for i in range(len(sizes) - 1)]
    lam = float(np.mean(ratios[-2:]))
    return lam, sizes, ratios


LAMBDA_EXACT = np.sqrt(4.0 + np.sqrt(15.0))   # = sqrt(Perron eigenvalue)
# The substitution count matrix of spectre.py has Perron eigenvalue
# 4 + sqrt(15) = 7.8729833... (verified numerically), so the linear
# inflation is lambda = sqrt(4+sqrt(15)) = 2.8058837... .  Note this is NOT
# phi^2 = 2.618 (the hat H7/H8 inflation); the spectre system used here has
# its own exact value, which the quad measurement converges to.


# ===========================================================================
# 2) structure factor of the tiling -> the template's origin
# ===========================================================================
def centroids(n_iterations=3):
    placements = TF.placed_tiles(n_iterations)
    canon = TF.canonical_tile_verts('x')[:14]
    return np.array([TF.transform_polygon(T, canon).mean(axis=0)
                     for T, _ in placements])


def structure_factor(pts, kmax=8.0, nk=4000):
    x = pts[:, 0] - pts[:, 0].mean()
    k = np.linspace(0.05, kmax, nk)
    S = np.abs(np.exp(1j * np.outer(k, x)).sum(axis=1)) ** 2 / len(x)
    return k, S


# ===========================================================================
# 3) log-periodic statistic
# ===========================================================================
def log_periodic_scan(f, P, fmin=20.0, fmax=1024.0, nlog=4096, med_win=101):
    """Return (lags, acf) of the whitened log-f spectrum autocorrelation."""
    m = (f >= fmin) & (f <= fmax) & np.isfinite(P) & (P > 0)
    lf = np.log(f[m]); lp = np.log(P[m])
    g = np.linspace(lf.min(), lf.max(), nlog)
    lp_g = np.interp(g, lf, lp)
    # whiten: subtract running median (removes smooth noise floor shape)
    from scipy.ndimage import median_filter
    resid = lp_g - median_filter(lp_g, size=med_win, mode='nearest')
    resid -= resid.mean()
    acf = np.correlate(resid, resid, mode='full')[nlog - 1:]
    if acf[0] <= 0:
        raise RuntimeError('whitened spectrum has no fluctuation power; '
                           'check the PSD (leakage-dominated?)')
    acf /= acf[0]
    dlag = g[1] - g[0]
    lags = np.arange(nlog) * dlag
    return lags, acf, resid, g


def comb_zscore(lags, acf, resid, ln_lambda, n_surrogates=200):
    """z-score of acf at lag ln(lambda) vs phase-randomised surrogates."""
    i0 = int(np.argmin(np.abs(lags - ln_lambda)))
    stat = acf[i0]
    n = len(resid)
    F = np.fft.rfft(resid)
    surro = np.empty(n_surrogates)
    for s in range(n_surrogates):
        ph = np.exp(2j * np.pi * RNG.random(len(F)))
        ph[0] = 1.0
        r = np.fft.irfft(F * ph, n=n)
        a = np.correlate(r, r, mode='full')[n - 1:]
        surro[s] = a[i0] / max(a[0], 1e-30)
    return (stat - surro.mean()) / surro.std(), stat, surro


# ===========================================================================
# 4) data
# ===========================================================================
from gwpy.timeseries import TimeSeries

def get_ligo_data(detector, start, end, rate=4096, cache_dir=CACHE):
    if not os.path.exists(cache_dir): os.makedirs(cache_dir)
    cache_file = os.path.join(cache_dir, f"{detector}_{start}_{end}.h5")
    if os.path.exists(cache_file):
        print('loading from cache')
        return TimeSeries.read(cache_file)
    print('downloading...')
    data = TimeSeries.fetch_open_data(detector, start, end, sample_rate=rate)
    data.write(cache_file, overwrite=True)
    return data

def load_strain(detector='L1', gps_start=1266624018, duration=500, fs=4096):
    """cache -> gwosc -> synthetic. Returns (data, fs, source_string)."""
    print('loading:', detector, gps_start, duration, fs)
    ts = get_ligo_data(detector, gps_start, gps_start+duration, fs)
    return np.asarray(ts.value), float(ts.sample_rate.value), 'gwosc'

def load_synth():
    # synthetic coloured noise with a rough aLIGO PSD shape.
    #    NB: band-limited (zero below 10 Hz).  A realistic f^-8 seismic wall
    #    is so steep that spectral leakage from low f dominates the whole
    #    band and produces a perfectly smooth monotone PSD, which breaks the
    #    whitening step -- and real data is high-passed anyway.
    n = duration * fs
    f = np.fft.rfftfreq(n, 1 / fs)
    with np.errstate(divide='ignore'):
        asd = 1e-23 * np.sqrt((30.0 / np.maximum(f, 1e-3)) ** 4
                              + 1.0 + (f / 700.0) ** 2)
    asd[f < 10.0] = 0.0
    noise_f = asd * (RNG.standard_normal(len(f))
                     + 1j * RNG.standard_normal(len(f))) * np.sqrt(n * fs) / 2
    data = np.fft.irfft(noise_f, n=n)
    # a few instrumental-style lines (mains harmonics + violin modes) so the
    # null test runs on something with realistic narrowband structure
    t = np.arange(n) / fs
    for fl, amp in [(60, 3e-22), (120, 1.5e-22), (180, 8e-23),
                    (500, 2e-22), (1000, 1e-22)]:
        data = data + amp * np.sin(2 * np.pi * fl * t + RNG.random() * 6.28)
    return data, float(fs), 'synthetic'


def inject_spectre_comb(data, fs, lam, f0=25.0, n_lines=8, snr_amp=6.0):
    """Add sinusoids at f0 * lam^n for the injection/validation run."""
    t = np.arange(len(data)) / fs
    sigma = data.std()
    out = data.copy()
    freqs = []
    for i in range(n_lines):
        fi = f0 * lam ** i
        if fi > fs / 2 * 0.9:
            break
        freqs.append(fi)
        out = out + snr_amp * sigma / np.sqrt(len(data)) * 70 \
            * np.sin(2 * np.pi * fi * t + RNG.random() * 2 * np.pi)
    return out, freqs


# ===========================================================================
def main():
    # -- 1: inflation factor ------------------------------------------------
    lam, sizes, ratios = measure_inflation(4)
    print(f'supertile quad diagonals: {[f"{s:.3f}" for s in sizes]}')
    print(f'iteration ratios:         {[f"{r:.5f}" for r in ratios]}')
    print(f'==> measured lambda = {lam:.6f}; exact sqrt(4+sqrt(15)) = {LAMBDA_EXACT:.6f}')
    lam = LAMBDA_EXACT
    print(f'    using exact lambda; ln(lambda) = {np.log(lam):.6f}')

    # -- 2: structure factor ------------------------------------------------
    pts = centroids(3)
    k, Sk = structure_factor(pts)
    pk, _ = find_peaks(Sk, height=Sk.max() * 0.15, distance=30)

    # -- 3+4: strain scans --------------------------------------------------
    data, fs, source = load_strain()
    print(f'strain source: {source}   fs={fs} Hz   n={len(data)}')

    def psd(x):
        return welch(x, fs=fs, nperseg=int(8 * fs), noverlap=int(4 * fs))

    results = {}
    f, P = psd(data)
    lags, acf, resid, g = log_periodic_scan(f, P)
    z, stat, surro = comb_zscore(lags, acf, resid, np.log(lam))
    results['data'] = (f, P, lags, acf, z)
    print(f'[data]      acf(ln lambda) = {stat:+.4f}   z = {z:+.2f}')

    inj, freqs = inject_spectre_comb(data, fs, lam)
    f2, P2 = psd(inj)
    lags2, acf2, resid2, g2 = log_periodic_scan(f2, P2)
    z2, stat2, _ = comb_zscore(lags2, acf2, resid2, np.log(lam))
    results['injection'] = (f2, P2, lags2, acf2, z2)
    print(f'[injection] acf(ln lambda) = {stat2:+.4f}   z = {z2:+.2f}   '
          f'lines at {[f"{x:.1f}" for x in freqs]} Hz')

    # -- figure -------------------------------------------------------------
    fig, axes = plt.subplots(2, 2, figsize=(14, 10))

    ax = axes[0, 0]
    ax.plot(k, Sk, lw=0.7, color='k')
    ax.plot(k[pk], Sk[pk], 'r.', ms=8)
    ax.set_xlabel('k'); ax.set_ylabel('S(k)')
    ax.set_title(f'1D structure factor of spectre centroids '
                 f'({len(pts)} tiles)\npeak hierarchy carries the '
                 f'inflation ratio $\\lambda$={lam:.4f}')

    ax = axes[0, 1]
    it = np.arange(1, len(sizes) + 1)
    ax.semilogy(it, sizes, 'o-')
    ax.set_xlabel('substitution iteration'); ax.set_ylabel('supertile scale')
    ax.set_title('inflation: scale $\\times\\,\\lambda$ per iteration\n'
                 f'$\\lambda=\\sqrt{{4+\\sqrt{{15}}}}$ = {lam:.6f}')
    ax.grid(alpha=0.3)

    for col, key in enumerate(['data', 'injection']):
        f_, P_, lags_, acf_, z_ = results[key]
        ax = axes[1, col]
        ax.plot(lags_, acf_, lw=0.8, color='navy')
        for m in (1, 2, 3):
            ax.axvline(m * np.log(lam), color='crimson', ls='--', alpha=0.6)
        ax.set_xlim(0, 4 * np.log(lam))
        ax.set_xlabel('lag in ln(f)'); ax.set_ylabel('ACF of whitened log-PSD')
        label = 'strain (no injection)' if key == 'data' else \
            'strain + injected spectre comb'
        ax.set_title(f'{label}  [{source}]\n'
                     f'z at ln$\\lambda$ = {z_:+.2f}'
                     + ('   <- pipeline validates' if key == 'injection' else ''))
        ax.grid(alpha=0.3)

    fig.tight_layout()
    png = os.path.join(OUT, 'ligo_spectre_search.png')
    fig.savefig(png, dpi=140)
    print(f'wrote {png}')

    with open(os.path.join(OUT, 'ligo_spectre_results.txt'), 'w') as fh:
        fh.write(f'lambda = {lam:.6f}  ln lambda = {np.log(lam):.6f}\n')
        fh.write(f'source = {source}\n')
        fh.write(f'z(data)      = {results["data"][4]:+.3f}\n')
        fh.write(f'z(injection) = {results["injection"][4]:+.3f}\n')
        fh.write('detection criterion: |z| > 4 at lag ln(lambda) with peak\n'
                 'also present at 2*ln(lambda) in BOTH H1 and L1.\n')


if __name__ == '__main__':
    main()
