#!/usr/bin/env python3
r"""spectrelean.py -- the Fact layer of the paper, as Lean 4 the kernel proves.

The companion suite checks every Fact twice, by two routes that share no code.
That is a good discipline and it is still two computations.  This is a third
thing, and a different kind: the closed statements among the Facts are put to
Lean 4, which proves them or does not compile.

What is and is not claimed here matters.

  * Lean sees the substitution matrix, the two charge vectors, the census
    recurrence, the Seifert minors and the arithmetic of Z[sqrt15].  Those are
    finite objects and closed identities, so `decide` and induction settle
    them outright.  Nothing is assumed and nothing is `sorry`.

  * Lean does not see the tiling.  That the matrix transcribes the published
    substitution is an auditable claim about a transcription, not a theorem,
    and the paper says so.  A kernel proof about M is a proof about M.

  * Lean does not see the modelling steps at all.  The birefringence
    candidate has a unit postulate in front of it; it is arithmetic over a
    premise, and putting the arithmetic in a kernel would dress the premise in
    a certificate it has not earned.

The file is deliberately Mathlib-free.  Everything is Int, List Int and
structures over them, so it compiles against a bare Lean toolchain in seconds
and anyone can check it without a package manager.  That costs some elegance --
Z[sqrt15] is spelt out as a pair rather than imported -- and buys the property
that the proof is as auditable as the Python.

    python3 spectrelean.py             write SpectreFacts.lean
    python3 spectrelean.py --stdout    print it
    python3 spectrelean.py --check     write it and run `lean` over it
"""

import os
import subprocess
import sys

import spectrefacts as F

HERE = os.path.dirname(os.path.abspath(__file__))
OUTPUT = os.path.join(HERE, 'SpectreFacts.lean')


def int_list(xs):
    return '[' + ', '.join(str(int(x)) for x in xs) + ']'


def matrix_rows(M):
    return ',\n   '.join(int_list(M.row(i)) for i in range(M.shape[0]))


PREAMBLE = r'''/-
  SpectreFacts.lean -- the Fact layer of

    "Exact spectral theory of the Spectre substrate"

  generated by spectrelean.py from spectrefacts.py.  Do not edit: edit the
  facts and regenerate, or the paper and the proof will disagree, which is the
  failure this file exists to make impossible.

  Mathlib-free on purpose.  Everything below is Int, List Int, or a structure
  over them, so `lean SpectreFacts.lean` against a bare toolchain checks it.

  The axiom audit below is measured, not asserted: spectrelean.py --check runs
  `#print axioms` over every theorem and writes the result in.  The final
  section lists what is NOT claimed.

%s-/

namespace Spectre

/-! ## The quoted input

The substitution matrix on nine species, in the order
(Gamma, Delta, Theta, Lambda, Xi, Pi, Sigma, Phi, Psi).  This is the one thing
taken on trust: that it transcribes the published substitution.  Everything
else is proved from it. -/

def M : List (List Int) :=
  [%s]

def dot (u v : List Int) : Int :=
  (List.zipWith (· * ·) u v).foldl (· + ·) 0

/-- A row vector times the matrix: the census charges act on the left. -/
def vecMul (q : List Int) (A : List (List Int)) : List Int :=
  (List.range 9).map (fun j => dot q ((List.range 9).map (fun i =>
    ((A.getD i []).getD j 0))))

/-- The matrix acting on a column of species counts. -/
def mulVec (A : List (List Int)) (v : List Int) : List Int :=
  A.map (fun row => dot row v)

def scale (c : Int) (v : List Int) : List Int := v.map (c * ·)

/-- Iterate the substitution `n` times from a seed census. -/
def iter : Nat -> List Int -> List Int
  | 0,     v => v
  | n + 1, v => mulVec M (iter n v)

def total (v : List Int) : Int := v.foldl (· + ·) 0
'''


def charges_section():
    qp = int_list(F.Q_PLUS)
    qm = int_list(F.Q_MINUS)
    seed = int_list([1 if n == 'Delta' else 0 for n in F.SPECIES])
    depths = ''.join(
        '\ntheorem charges_at_depth_%d :\n'
        '    dot Qplus (iter %d seed) = %d \u2227 dot Qminus (iter %d seed) = %d := by\n'
        '  decide\n' % (d, d, F.Q_PLUS_BY_DEPTH[d - 1], d, F.Q_MINUS_BY_DEPTH[d - 1])
        for d in range(1, 5))
    return r'''
/-! ## The two marginal charges

`Qplus` and `Qminus` are left eigenvectors of M for the eigenvalues +1 and -1.
Being finite integer identities, they are decided outright. -/

def Qplus  : List Int := %s
def Qminus : List Int := %s

/-- The seed census: one Delta. -/
def seed : List Int := %s

theorem q_plus_is_invariant : vecMul Qplus M = Qplus := by decide

theorem q_minus_alternates : vecMul Qminus M = scale (-1) Qminus := by decide

/-! The charges evaluated on the patches of depth one to four.  These are the
numbers the paper prints.  Note which census they eat: `iter` applies M, so
the vector here is the nine-species one, with the Mystic counted by
`mystic_is_previous_total` below rather than folded into Gamma. -/
%s''' % (qp, qm, seed, depths)


def census_section():
    totals = F.MATRIX_TOTALS[:5]
    geom = F.GEOMETRIC_TOTALS[:5]
    lines = ''.join(
        '\ntheorem census_total_%d : total (iter %d seed) = %d := by decide\n'
        % (d, d, totals[d]) for d in range(5))
    rec = ''.join(
        '\ntheorem recurrence_%d :\n'
        '    total (iter %d seed) = 8 * total (iter %d seed) - total (iter %d seed) := by\n'
        '  decide\n' % (d, d, d - 1, d - 2) for d in range(3, 5))
    mystic = ''.join(
        '\ntheorem mystic_%d :\n'
        '    (iter %d seed).getD 0 0 = total (iter %d seed) := by decide\n'
        % (d, d, d - 1) for d in range(1, 5))
    geo = ''.join(
        '\ntheorem geometric_total_%d :\n'
        '    total (iter %d seed) + total (iter %d seed) = %d := by decide\n'
        % (d, d, d - 1, geom[d]) for d in range(1, 5))
    return r'''
/-! ## The census, and the Mystic

The matrix census runs 1, 8, 63, 496, 3905.  A placed patch also carries the
Mystic, and its count is not an extra convention to remember: row Gamma of M
is all ones, so the Gamma entry at depth n is the whole census at depth n-1,
and the geometric total is the matrix total plus its predecessor.  The paper
used to state the two totals in different sections without this identity
between them. -/

theorem row_Gamma_is_all_ones : M.getD 0 [] = List.replicate 9 1 := by decide
%s%s
/-- The Gamma entry at depth n is the total at depth n-1: the Mystic is a
second copy of the previous generation, not an independent count. -/%s
/-- Hence the geometric totals 9, 71, 559, 4401. -/%s''' % (lines, rec, mystic, geo)


def arithmetic_section():
    return r'''
/-! ## Arithmetic in Z[sqrt 15]

`Z15 a b` is `a + b * sqrt 15`.  Writing the ring out by hand rather than
importing it is what keeps this file Mathlib-free; the cost is four lines, and
the identities below are then `decide`.

The point of doing the channel identities here is that they are proved
*without evaluating a square root*: sqrt 6 and sqrt 10 never appear.  What is
proved is that the square of `lam - lam⁻¹` is the rational integer 6, and the
square of `lam + lam⁻¹` is 10. -/

structure Z15 where
  a : Int
  b : Int
deriving DecidableEq, Repr

instance : Add Z15 := ⟨fun x y => ⟨x.a + y.a, x.b + y.b⟩⟩
instance : Sub Z15 := ⟨fun x y => ⟨x.a - y.a, x.b - y.b⟩⟩
instance : Mul Z15 := ⟨fun x y => ⟨x.a * y.a + 15 * x.b * y.b,
                                   x.a * y.b + x.b * y.a⟩⟩

/-- `lam2` is lambda squared, the Perron eigenvalue 4 + sqrt 15. -/
def lam2 : Z15 := ⟨4, 1⟩

/-- Its conjugate, which is also its inverse. -/
def lam2inv : Z15 := ⟨4, -1⟩

/-- The Pell identity: 4² - 15·1² = 1, so `lam2` is a unit -- and being the
least solution, the fundamental unit of Z[sqrt 15]. -/
theorem pell_fundamental_unit : lam2 * lam2inv = ⟨1, 0⟩ := by decide

/-- No smaller positive solution exists, checked by exhaustion below the
fundamental one. -/
theorem pell_is_least :
    ∀ y : Fin 1, ∀ x : Fin 4, ¬ ((x.val : Int)^2 - 15 * ((y.val : Int) + 1)^2 = 1) := by
  decide

/-- The contraction rate per substitution step: lambda⁻⁴ = 31 - 8 sqrt 15. -/
theorem contraction_rate : lam2inv * lam2inv = ⟨31, -8⟩ := by decide

/-- The hexagonal channel: (lambda - lambda⁻¹)² = lambda² + lambda⁻² - 2 = 6. -/
theorem channel_hexagonal : lam2 + lam2inv - ⟨2, 0⟩ = ⟨6, 0⟩ := by decide

/-- The pentagonal channel: (lambda + lambda⁻¹)² = lambda² + lambda⁻² + 2 = 10. -/
theorem channel_pentagonal : lam2 + lam2inv + ⟨2, 0⟩ = ⟨10, 0⟩ := by decide

/-- Both channels are rational integers: the sqrt 15 part cancels. Stated
separately because it is the content -- a biquadratic field appearing as two
quadratic channels. -/
theorem channels_are_rational :
    (lam2 + lam2inv).b = 0 := by decide
'''


def minors_section():
    return r'''
/-! ## The Seifert form of T(2,k), for every k at once

The Seifert form of the (2,k) torus knot is the (k-1)-dimensional tridiagonal
matrix with -2 on the diagonal and 1 beside it.  Its leading principal minors
obey `D (m+2) = -2 * D (m+1) - D m`, and the paper checks negative
definiteness by computing them for a few values of k.

Here the closed form is proved for all m by induction, which upgrades a
sampled check into a statement about the whole family: the minors alternate in
sign forever, so Sylvester's criterion gives negative definiteness at every k,
hence signature -(k-1) and the unknotting bound at every k. -/

/-- Leading principal minors of the tridiagonal (-2, 1, 1) form. -/
def D : Nat → Int
  | 0     => 1
  | 1     => -2
  | n + 2 => -2 * D (n + 1) - D n

/-- The closed form, with the sign carried explicitly so that no power of -1
is needed. -/
def Dclosed (m : Nat) : Int :=
  if m % 2 = 0 then (m + 1 : Int) else -((m : Int) + 1)

/-- Two-step induction, carried as a pair so that plain `Nat.rec` suffices and
no strong-induction principle has to be imported. -/
theorem D_closed_pair :
    ∀ m : Nat, D m = Dclosed m ∧ D (m + 1) = Dclosed (m + 1) := by
  intro m
  induction m with
  | zero => exact ⟨rfl, rfl⟩
  | succ n ih =>
    cases ih with
    | intro h0 h1 =>
      refine ⟨h1, ?_⟩
      show -2 * D (n + 1) - D n = Dclosed (n + 2)
      rw [h1, h0]
      simp only [Dclosed]
      rcases Nat.mod_two_eq_zero_or_one n with e0 | e0
      · have e1 : (n + 1) % 2 = 1 := by omega
        have e2 : (n + 2) % 2 = 0 := by omega
        simp [e0, e1, e2]
        omega
      · have e1 : (n + 1) % 2 = 0 := by omega
        have e2 : (n + 2) % 2 = 1 := by omega
        simp [e0, e1, e2]
        omega

theorem seifert_minor_closed_form (m : Nat) : D m = Dclosed m :=
  (D_closed_pair m).1

/-- The minors are never zero, so Sylvester's criterion applies at every size,
and they alternate in sign, so the form is negative definite for every k. -/
theorem minors_alternate (m : Nat) :
    (m % 2 = 0 → D m > 0) ∧ (m % 2 = 1 → D m < 0) := by
  rw [seifert_minor_closed_form]
  refine ⟨fun h => ?_, fun h => ?_⟩
  · have e : Dclosed m = (m : Int) + 1 := by simp [Dclosed, h]
    rw [e]; omega
  · have e : Dclosed m = -((m : Int) + 1) := by simp [Dclosed, h]
    rw [e]; omega
'''


def frequency_section():
    pairs = ', '.join('(%d, %d)' % (int(F.FREQ_Z15[n][0]), int(F.FREQ_Z15[n][1]))
                      for n in F.SPECIES)
    hat = ', '.join('(%d, %d)' % p for p in F.HAT_FREQ_Z5)
    return r'''
/-! ## The eigenvector, as an eigenvector

The nine frequencies are not merely in Q(sqrt 15): the denominators clear, so
they are algebraic integers and the whole eigenvector equation lives in
Z[sqrt 15].  That is what lets the kernel check it with `decide` rather than
with rational arithmetic it does not have.

This is the check the companion suite does componentwise by substitution.
Here it is one proposition. -/

def freq : List Z15 :=
  [%s].map (fun p => ⟨p.1, p.2⟩)

def z15dot (row : List Int) (v : List Z15) : Z15 :=
  (List.zipWith (fun (c : Int) (z : Z15) => ⟨c * z.a, c * z.b⟩) row v).foldl
    (· + ·) ⟨0, 0⟩

/-- M f = lambda² f, componentwise, over Z[sqrt 15]. -/
theorem frequencies_are_an_eigenvector :
    M.map (fun row => z15dot row freq) = freq.map (fun z => lam2 * z) := by
  decide

/-- And they sum to one, so they are frequencies and not merely a direction. -/
theorem frequencies_sum_to_one :
    freq.foldl (· + ·) ⟨0, 0⟩ = ⟨1, 0⟩ := by decide

/-! ## Aperiodicity, as irrationality

A periodic tiling has a fundamental domain, in which every species occurs a
whole number of times; so in a periodic tiling every relative frequency is
rational.  One irrational frequency therefore refutes periodicity.

Which frequency does the refuting is where the two phases differ.  Every
Spectre frequency has a nonzero sqrt 15 part, so every species is a witness.
The Hat has four metatiles and its commonest is exactly one third -- rational,
and so no witness at all.  The Hat's aperiodicity has to be read off a rarer
tile; the Spectre's can be read off any. -/

theorem every_spectre_frequency_is_irrational :
    ∀ z ∈ freq, z.b ≠ 0 := by decide

/-- The Hat frequencies, scaled by six to clear denominators, as pairs
`a + b sqrt 5`. -/
def hatFreq6 : List (Int × Int) := [%s]

/-- Exactly one Hat frequency is rational, and it is the first, the H
metatile: six times it is 2, with no sqrt 5 part. -/
theorem hat_has_exactly_one_rational_frequency :
    (hatFreq6.filter (fun p => p.2 = 0)).length = 1 := by decide

theorem hat_H_frequency_is_one_third :
    hatFreq6.getD 0 (0, 0) = (2, 0) := by decide

/-! ## Trace accounting

The marginal pair +1 and -1 cancels and the zero modes contribute nothing, so
in both phases the trace is the Perron unit plus its conjugate.  The same
accounting in two different quadratic fields. -/

theorem trace_is_unit_plus_conjugate :
    lam2 + lam2inv = ⟨8, 0⟩ := by decide

theorem spectre_trace_is_eight :
    ((List.range 9).map (fun i => (M.getD i []).getD i 0)).foldl (· + ·) 0
      = 8 := by decide
'''  % (pairs, hat)


def chiral_section():
    return r'''
/-! ## The measured chiral angle, and where it comes from

Moritake et al. measured the twist of the Hat quasilattice's diffraction and
give its cosine as (3 phi - 1)/4.  The Hat inflation factor is kappa = phi^4.
These are the same number shifted: 3 phi - 1 = kappa - 3, so the angle a
laboratory measured is a function of the eigenvalue this file already proves
things about.

Written over Z[sqrt 5], cleared of denominators: 8 cos theta = 1 + 3 sqrt 5
and 2 kappa = 7 + 3 sqrt 5, so 8 cos theta = 2 kappa - 6. -/

structure Z5 where
  a : Int
  b : Int
deriving DecidableEq, Repr

instance : Add Z5 := ⟨fun x y => ⟨x.a + y.a, x.b + y.b⟩⟩
instance : Sub Z5 := ⟨fun x y => ⟨x.a - y.a, x.b - y.b⟩⟩
instance : Mul Z5 := ⟨fun x y => ⟨x.a * y.a + 5 * x.b * y.b,
                                  x.a * y.b + x.b * y.a⟩⟩

/-- Twice the Hat inflation factor: 2 kappa = 7 + 3 sqrt 5. -/
def twoKappa : Z5 := ⟨7, 3⟩

/-- Eight times the measured chiral cosine: 1 + 3 sqrt 5. -/
def eightCos : Z5 := ⟨1, 3⟩

/-- The measured angle is the inflation factor, shifted and scaled. -/
theorem chiral_angle_from_inflation : eightCos = twoKappa - ⟨6, 0⟩ := by decide

/-- kappa satisfies the Hat quadratic, so the constant in the angle is not
free: twice it is a root of x^2 - 14x + 4. -/
theorem two_kappa_quadratic :
    twoKappa * twoKappa = ⟨14, 0⟩ * twoKappa - ⟨4, 0⟩ := by decide
'''


def xcharge_section():
    vals = ', '.join(str(v) for k, v in sorted(F.X_CHARGE.items())
                     if not isinstance(v, tuple))
    return r'''
/-! ## The X-charges are even

The per-species X-charges are measured, not derived: `spectreatlas.py` builds
the tiling and counts bonds.  What the kernel can settle is the arithmetic
claim made about them -- that every one is even, which is what lets the
binding spectrum be written as 2 delta times a small set of integers.

Phi is the exception that has to be stated: it carries 0 or 2 depending on its
collar, never 1, so the evenness survives the flavour split. -/

def xCharges : List Int := [%s, 0, 2]

theorem x_charges_are_even : ∀ x ∈ xCharges, x %% 2 = 0 := by decide

/-- The Mystic is saturated: all fourteen of its slots are X-bonds. -/
theorem mystic_is_saturated : xCharges.contains 14 = true := by decide

/-- The binding spectrum is 2 delta times {0, 1, 2, 7}: the charges halved
land in that set, and every member of it is attained. -/
theorem binding_spectrum_lands_in :
    ∀ x ∈ xCharges, (x / 2) ∈ [(0 : Int), 1, 2, 7] := by decide

theorem binding_spectrum_is_attained :
    ([(0 : Int), 1, 2, 7]).all
      (fun v => (xCharges.map (fun x => x / 2)).contains v) = true := by
  decide
''' % vals


def limits_section():
    return r'''
/-! ## What is not claimed

Stated as comments rather than as theorems, because a comment cannot be
mistaken for a certificate.

  * That `M` transcribes the published Spectre substitution.  This is the one
    quoted input.  It is auditable -- the companion suite rebuilds the census
    from the placement chain geometrically and agrees at every depth -- but it
    is a claim about a transcription, and no proof here bears on it.

  * That the Spectre phase is the admissible one on a two-dimensional
    conformal screen.  That is Conjecture 1 and it is a selection argument,
    not arithmetic.

  * Anything downstream of the unit postulate, including the birefringence
    candidate.  The arithmetic there is elementary and correct; its premise is
    a modelling step, and certifying the arithmetic would lend the premise a
    credibility it has not earned.

  * The identification of the tiling's edge braids with the (2,k) torus knots.
    The knot facts above are theorems about T(2,k); that the substrate
    presents those knots is a modelling step.
-/

end Spectre
'''


def document(audit=None):
    return (PREAMBLE % (audit or AUDIT_PENDING, matrix_rows(F.M))
            + charges_section()
            + census_section()
            + arithmetic_section()
            + frequency_section()
            + xcharge_section()
            + chiral_section()
            + minors_section()
            + limits_section())


AUDIT_SENTENCE = (
    'The axiom audit is measured rather than asserted: \\code{\\#print axioms} is run '
    'over every theorem and the result written into the file header. No proof '
    'is admitted, and nothing depends on \\code{Classical.choice}, so every proof '
    'in the file is constructive.')

AUDIT_PENDING = ('  AXIOM AUDIT: not yet run.  Use spectrelean.py --check.\n')


def audit_block(output):
    """Turn `#print axioms` output into the header block, truthfully."""
    clean, used = [], {}
    for line in output.splitlines():
        if 'does not depend on any axioms' in line:
            clean.append(line.split("'")[1])
        elif 'depends on axioms' in line:
            name = line.split("'")[1]
            used[name] = line.split('axioms: ')[1].strip()
    lines = ['  AXIOM AUDIT (measured by `#print axioms` on every theorem):',
             '',
             '    %d theorems depend on no axioms at all.' % len(clean)]
    if used:
        every = sorted(set(a for v in used.values() for a in
                           v.strip('[]').split(', ')))
        lines.append('    %d depend on %s -- the standard Lean foundation.'
                     % (len(used), ', '.join(every)))
        lines.append('    They are the induction proofs; `simp` and `omega`')
        lines.append('    bring these in. Classical.choice appears nowhere, so')
        lines.append('    every proof here is constructive.')
    lines.append('    sorryAx appears nowhere: nothing is admitted.')
    lines.append('')
    return '\n'.join(lines) + '\n'


def write(path=OUTPUT, audit=None):
    text = document(audit)
    with open(path, 'w') as handle:
        handle.write(text)
    return path


def theorem_names(text):
    import re
    return re.findall(r'^theorem\s+([A-Za-z_0-9]+)', text, re.M)


def check(path=OUTPUT, lean='lean'):
    """Write the file, prove it, audit its axioms, then write it again.

    Two passes, because the header states the audit and the audit needs the
    file. The alternative is a header that claims something nobody measured,
    which is the habit this whole arrangement exists to break.
    """
    write(path)
    text = document()
    names = theorem_names(text)
    try:
        proc = subprocess.run([lean, path], capture_output=True, text=True,
                              timeout=900)
    except FileNotFoundError:
        print('no `lean` on PATH -- wrote %s but did not check it' % path)
        return 2
    if proc.returncode != 0:
        print(proc.stdout)
        print(proc.stderr)
        return 1

    probe = os.path.join(HERE, '_audit.lean')
    body = text.replace('end Spectre', '')
    with open(probe, 'w') as handle:
        handle.write(body + '\n'
                     + '\n'.join('#print axioms %s' % n for n in names)
                     + '\n\nend Spectre\n')
    audited = subprocess.run([lean, probe], capture_output=True, text=True,
                             timeout=900)
    os.remove(probe)
    if 'sorryAx' in audited.stdout:
        print('a theorem is admitted rather than proved')
        return 1
    write(path, audit_block(audited.stdout))
    again = subprocess.run([lean, path], capture_output=True, text=True,
                           timeout=900)
    if again.returncode != 0:
        print(again.stdout)
        return 1
    print('SpectreFacts.lean: %d theorems, kernel accepted.' % len(names))
    print(audit_block(audited.stdout).replace('  ', '', 1))
    return 0


if __name__ == '__main__':
    if '--stdout' in sys.argv:
        print(document())
    elif '--check' in sys.argv:
        sys.exit(check())
    else:
        print('wrote ' + write())
